services:
  server:
    env_file:
      - ./.env
    build: .
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - $LOCAL_PORT:$DOCKER_PORT
    
    depends_on:
      mysqldb:
        # waits to mysql be ready
        condition: service_healthy
    volumes:
      - .:/home/app

  mysqldb:
    image: mysql
    env_file:
      - ./.env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
volumes:
  mysql-data:

