services:
  server:
    env_file:
      - ./.env
    build: .
    ports:
      - $LOCAL_PORT:$DOCKER_PORT
    links:
      - mysqldb
    depends_on:
      - mysqldb
    volumes:
      - .:/home/app

  mysqldb:
    image: mysql
    env_file:
      - ./.env
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    volumes:
      - mysql-data:/var/lib/mysql
  
volumes:
  mysql-data:

